name: Dotfiles Installation

on:
  push:
    branches:
      - master
  pull_request_target:
  workflow_dispatch:

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2

      - name: Install using Makefile
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            make
          else
            sudo make
          fi

      - name: Verify runcom setup
        run: source $HOME/.bash_profile

      - name: Run tests
        if: matrix.os == 'macos-latest'
        run: make test
      
      - uses: ntsd/auto-request-changes-action@v2
        if: ${{ github.event.pull_request && failure() }}
        with:
          comment-body: "The job ran failed please fix it."

      - uses: hmarr/auto-approve-action@v2
        if: ${{ github.event.pull_request && success() }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
